export default [
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5f7cc5144fdb22597262',
    },
    {
        title: 'Best apartment ever',
        text: 'This neighborhood is not good',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5f7cc5144fdb22597262',
    },
    {
        title: 'Best apartment ever',
        text: 'Its good but bugs everywhere',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5f7cc5144fdb22597262',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5f7cc5144fdb22597262',
    },
    {
        title: 'Best apartment ever',
        text: 'This is clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5f7cc5144fdb22597262',
    },
    {
        title: 'Best apartment ever',
        text: 'Management is good, but its a not a clean complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5f7cc5144fdb22597262',
    },
    {
        title: 'Best apartment ever',
        text: 'Lot of crimes, and management is not good',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5fbbc5144fdb22597267',
    },
    {
        title: 'Best apartment ever',
        text: 'Good neighborhood for kids and school',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5fbbc5144fdb22597267',
    },
    {
        title: 'Best apartment ever',
        text: 'Place for young professionals. Not so quiet on the weekends',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5fbbc5144fdb22597267',
    },
    {
        title: 'Best apartment ever',
        text: 'Management is rude, and not a place to live in',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5fbbc5144fdb22597267',
    },
    {
        title: 'Best apartment ever',
        text: 'Neighbors are awful. Management is not good',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5ff6c5144fdb2259726c',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet place.',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5ff6c5144fdb2259726c',
    },
    {
        title: 'Best apartment ever',
        text: 'Police come everyday. Crime filled complex.',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5ff6c5144fdb2259726c',
    },
    {
        title: 'Best apartment ever',
        text: 'Happy to be here. Great place.',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5ff6c5144fdb2259726c',
    },
    {
        title: 'Best apartment ever',
        text: 'Moved in recently. Shocked by the bugs everywhere',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc5ff6c5144fdb2259726c',
    },
    {
        title: 'Best apartment ever',
        text: 'All good expect for Lindsay in the leasing office. Management is just careless',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc6020c5144fdb22597271',
    },
    {
        title: 'Best apartment ever',
        text: 'I chose this neighborhood as its has good schools. Overall, am satisfied.',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc6020c5144fdb22597271',
    },
    {
        title: 'Best apartment ever',
        text: 'Listen to me -- dont come here. Not clean and not maintained.',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc6020c5144fdb22597271',
    },
    {
        title: 'Best apartment ever',
        text: 'Quiet and great living.',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc6020c5144fdb22597271',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: '62fc6020c5144fdb22597271',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
    {
        title: 'Best apartment ever',
        text: 'This is a quiet, clean apartment complex',
        rentRating: '7',
        petFriendlyRating: '9',
        gatedRating: '7',
        InUnitWasherDryerRating: '6',
        poolRating: '5',
        fitnessCenterRating: '8',
        parkingRating: '5',
        amenitiesRating: '9',
        reviewsScore: 10,
        apartment: 'a1',
    },
];
